### ISSUE TITLE
pitoganzado@gmail.com

### ISSUE THREAD

**Issue by pitoganzado** [xaviml/z2m_ikea_controller#1]
i'm getting this error when i add to HACS:

An error ocoured while prosessing
['Repostitory structure not compliant']
Could not add this repository, make sure it is compliant with HACS.

Any way to resolve it?
thanks!

**Comment by pitoganzado** [comment]
missing AppDaemon: true in configuration.yaml

**Comment by xaviml** [comment]
You mean the "appdaemon: true" inside the hacs integrarion?

I am glad everything is working now then :)
