### ISSUE TITLE
Errors on switching groups

### ISSUE THREAD

**Issue by corgan2222** [xaviml/z2m_ikea_controller#3]
Hello

i tryed your controller and ran into some errors.
If i only control one light (tryed different HUE Gos, Stripes aso) it nearly runs fine. 
On/Off and dimming works. Only the "arrow_right_click" and "arrow_left_click" has no function.
Is there a way to loop through colors?

But if im trying to run this on a group only ON/OF Works. No dimming.

group:

> office_light:
>   module: z2m_ikea_controller
>   class: E1810Controller
>   sensor: sensor.switch_office_ikea_action
>   light: group.grp_office2
>   manual_steps: 10
>   automatic_steps: 10
>   delay: 350

groups.yaml

>  grp_office2:
>     name: grp_office2 
> entities:
>     - light.hue_go_2
>     - light.buro_stribe_oben    
>     - light.buro_stripe_fenster
>     - light.hue_go_1
>     - light.buro_lampe
>     - light.buro_stripe_schreibtisch
> 

Errors:

> [14:06:40] INFO: Starting AppDaemon...
> 2020-01-03 14:06:42.391978 INFO AppDaemon Version 3.0.5 starting
> 2020-01-03 14:06:42.392427 INFO Configuration read from: /config/appdaemon/appdaemon.yaml
> 2020-01-03 14:06:42.396381 INFO AppDaemon: Starting Apps
> 2020-01-03 14:06:42.404093 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
> 2020-01-03 14:06:42.618902 INFO AppDaemon: HASS: HASS Plugin Initializing
> 2020-01-03 14:06:42.619654 INFO AppDaemon: HASS: HASS Plugin initialization complete
> 2020-01-03 14:06:42.620232 INFO Dashboards are disabled
> 2020-01-03 14:06:42.620495 INFO API is disabled
> 2020-01-03 14:06:42.634363 INFO AppDaemon: HASS: Connected to Home Assistant 0.103.5
> 2020-01-03 14:06:42.735547 INFO AppDaemon: Got initial state from namespace default
> 2020-01-03 14:06:44.844279 INFO AppDaemon: Reading config
> 2020-01-03 14:06:44.855316 INFO AppDaemon: /config/appdaemon/apps/apps.yaml added or modified
> 2020-01-03 14:06:44.855630 INFO AppDaemon: /config/appdaemon/apps/apps.yaml added or modified
> 2020-01-03 14:06:44.855902 INFO AppDaemon: App 'office_light' added
> 2020-01-03 14:06:44.856149 INFO AppDaemon: App 'check_config' added
> 2020-01-03 14:06:44.856669 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
> 2020-01-03 14:06:44.857126 INFO AppDaemon: Adding /config/appdaemon/apps/z2m_ikea_controller to module import path
> 2020-01-03 14:06:44.857558 INFO AppDaemon: Adding /config/appdaemon/apps/check-config to module import path
> 2020-01-03 14:06:44.858481 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/z2m_ikea_controller/z2m_ikea_controller.py
> 2020-01-03 14:06:44.874622 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/check-config/checkconfig.py
> 2020-01-03 14:06:44.875876 INFO AppDaemon: Initializing app office_light using class E1810Controller from module z2m_ikea_controller
> 2020-01-03 14:06:44.876422 INFO AppDaemon: Initializing app check_config using class CheckConfig from module checkconfig
> 2020-01-03 14:06:44.995844 INFO AppDaemon: App initialization complete
> 2020-01-03 14:07:10.481449 WARNING AppDaemon: ------------------------------------------------------------
> 2020-01-03 14:07:10.481865 WARNING AppDaemon: Unexpected error in worker for App office_light:
> 2020-01-03 14:07:10.482249 WARNING AppDaemon: Worker Ags: {'name': 'office_light', 'id': UUID('4a21da2f-adf5-49df-a74b-92e586893d82'), 'type': 'attr', 'function': <bound method IkeaController.state of <z2m_ikea_controller.E1810Controller object at 0xb4b79850>>, 'attribute': 'state', 'entity': 'sensor.switch_office_ikea_action', 'new_state': 'brightness_up_click', 'old_state': '', 'kwargs': {'handle': UUID('28768823-559e-4409-8f57-a6d81887fa26')}}
> 2020-01-03 14:07:10.482491 WARNING AppDaemon: ------------------------------------------------------------
> 2020-01-03 14:07:10.490500 WARNING AppDaemon: ------------------------------------------------------------
> 2020-01-03 14:07:10.496304 WARNING AppDaemon: Unexpected error in worker for App office_light:
> 2020-01-03 14:07:10.497154 WARNING AppDaemon: Worker Ags: {'name': 'office_light', 'id': UUID('4a21da2f-adf5-49df-a74b-92e586893d82'), 'type': 'attr', 'function': <bound method IkeaController.state of <z2m_ikea_controller.E1810Controller object at 0xb4b79850>>, 'attribute': 'state', 'entity': 'sensor.switch_office_ikea_action', 'new_state': 'brightness_up_click', 'old_state': 'brightness_up_click', 'kwargs': {'handle': UUID('28768823-559e-4409-8f57-a6d81887fa26')}}
> 2020-01-03 14:07:10.497394 WARNING AppDaemon: ------------------------------------------------------------
> 2020-01-03 14:07:10.516978 WARNING AppDaemon: Traceback (most recent call last):
>   File "/usr/lib/python3.7/site-packages/appdaemon/appdaemon.py", line 595, in worker
>     self.sanitize_state_kwargs(app, args["kwargs"]))
>   File "/config/appdaemon/apps/z2m_ikea_controller/z2m_ikea_controller.py", line 70, in state
>     self.turn_on_light(attribute, value, sign, self.manual_steps)
>   File "/config/appdaemon/apps/z2m_ikea_controller/z2m_ikea_controller.py", line 96, in turn_on_light
>     new_state_attribute = old + sign * step
> TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
> 
> 2020-01-03 14:07:10.517844 WARNING AppDaemon: Traceback (most recent call last):
>   File "/usr/lib/python3.7/site-packages/appdaemon/appdaemon.py", line 595, in worker
>     self.sanitize_state_kwargs(app, args["kwargs"]))
>   File "/config/appdaemon/apps/z2m_ikea_controller/z2m_ikea_controller.py", line 70, in state
>     self.turn_on_light(attribute, value, sign, self.manual_steps)
>   File "/config/appdaemon/apps/z2m_ikea_controller/z2m_ikea_controller.py", line 96, in turn_on_light
>     new_state_attribute = old + sign * step
> TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
> 
> 2020-01-03 14:07:10.518100 WARNING AppDaemon: ------------------------------------------------------------
> 2020-01-03 14:07:10.518330 WARNING AppDaemon: ------------------------------------------------------------
> 2020-01-03 14:07:46.204777 WARNING AppDaemon: ------------------------------------------------------------
> 2020-01-03 14:07:46.205412 WARNING AppDaemon: Unexpected error in worker for App office_light:
> 2020-01-03 14:07:46.206014 WARNING AppDaemon: Worker Ags: {'name': 'office_light', 'id': UUID('4a21da2f-adf5-49df-a74b-92e586893d82'), 'type': 'attr', 'function': <bound method IkeaController.state of <z2m_ikea_controller.E1810Controller object at 0xb4b79850>>, 'attribute': 'state', 'entity': 'sensor.switch_office_ikea_action', 'new_state': 'arrow_right_click', 'old_state': '', 'kwargs': {'handle': UUID('28768823-559e-4409-8f57-a6d81887fa26')}}
> 2020-01-03 14:07:46.206571 WARNING AppDaemon: ------------------------------------------------------------
> 2020-01-03 14:07:46.215012 WARNING AppDaemon: Traceback (most recent call last):
>   File "/usr/lib/python3.7/site-packages/appdaemon/appdaemon.py", line 595, in worker
>     self.sanitize_state_kwargs(app, args["kwargs"]))
>   File "/config/appdaemon/apps/z2m_ikea_controller/z2m_ikea_controller.py", line 70, in state
>     self.turn_on_light(attribute, value, sign, self.manual_steps)
>   File "/config/appdaemon/apps/z2m_ikea_controller/z2m_ikea_controller.py", line 96, in turn_on_light
>     new_state_attribute = old + sign * step
> TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
> 
> 2020-01-03 14:07:46.215758 WARNING AppDaemon: ------------------------------------------------------------
> 2020-01-03 14:07:46.216676 WARNING AppDaemon: ------------------------------------------------------------
> 2020-01-03 14:07:46.217146 WARNING AppDaemon: Unexpected error in worker for App office_light:
> 2020-01-03 14:07:46.217968 WARNING AppDaemon: Worker Ags: {'name': 'office_light', 'id': UUID('4a21da2f-adf5-49df-a74b-92e586893d82'), 'type': 'attr', 'function': <bound method IkeaController.state of <z2m_ikea_controller.E1810Controller object at 0xb4b79850>>, 'attribute': 'state', 'entity': 'sensor.switch_office_ikea_action', 'new_state': 'arrow_right_click', 'old_state': 'arrow_right_click', 'kwargs': {'handle': UUID('28768823-559e-4409-8f57-a6d81887fa26')}}
> 2020-01-03 14:07:46.218539 WARNING AppDaemon: ------------------------------------------------------------
> 2020-01-03 14:07:46.225092 WARNING AppDaemon: Traceback (most recent call last):
>   File "/usr/lib/python3.7/site-packages/appdaemon/appdaemon.py", line 595, in worker
>     self.sanitize_state_kwargs(app, args["kwargs"]))
>   File "/config/appdaemon/apps/z2m_ikea_controller/z2m_ikea_controller.py", line 70, in state
>     self.turn_on_light(attribute, value, sign, self.manual_steps)
>   File "/config/appdaemon/apps/z2m_ikea_controller/z2m_ikea_controller.py", line 96, in turn_on_light
>     new_state_attribute = old + sign * step
> TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
> 
> 2020-01-03 14:07:46.225878 WARNING AppDaemon: ------------------------------------------------------------

System | Raspbian GNU/Linux 10 (buster)
with manually installed zigbee2mqtt, mqtt broker and hass.io on top 
latest versions

**Comment by corgan2222** [comment]
on/off
`{"linkquality":39,"battery":74,"action":"","device":{"friendlyName":"switch.office.ikea","model":"E1524/E1810","ieeeAddr":"0x14b457fffe734e84","networkAddress":6587,"type":"EndDevice","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","powerSource":"Battery","applicationVersion":32,"stackVersion":87,"zclVersion":1,"hardwareVersion":1,"dateCode":"20190211","softwareBuildID":"1.2.223"}}`

upClick

`{"linkquality":36,"battery":74,"action":"brightness_up_click","device":{"friendlyName":"switch.office.ikea","model":"E1524/E1810","ieeeAddr":"0x14b457fffe734e84","networkAddress":6587,"type":"EndDevice","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","powerSource":"Battery","applicationVersion":32,"stackVersion":87,"zclVersion":1,"hardwareVersion":1,"dateCode":"20190211","softwareBuildID":"1.2.223"}}`

arrow click


`{"linkquality":39,"battery":74,"action":"arrow_right_click","device":{"friendlyName":"switch.office.ikea","model":"E1524/E1810","ieeeAddr":"0x14b457fffe734e84","networkAddress":6587,"type":"EndDevice","manufacturerID":4476,"manufacturerName":"IKEA of Sweden","powerSource":"Battery","applicationVersion":32,"stackVersion":87,"zclVersion":1,"hardwareVersion":1,"dateCode":"20190211","softwareBuildID":"1.2.223"}}`

**Comment by xaviml** [comment]
Hi corgan2222,

Could you please provide the state attributes when the state of the group.grp_office2 is on?

**Comment by corgan2222** [comment]
Hey, thanxs for the quick reply

developer-tools/state:

off:
group.grp_office2 | off | entity_id: light.buro_stripe_fenster,light.hue_go_1,light.buro_lampe,light.buro_stripe_schreibtisch order: 3 friendly_name: grp_office2

on
group.grp_office2 | on | entity_id: light.buro_stripe_fenster,light.hue_go_1,light.buro_lampe,light.buro_stripe_schreibtisch order: 3 friendly_name: grp_office2
-- | -- | --






In the window with the controls its written in german AN/AUS

**Comment by xaviml** [comment]
Okay thanks, and what do you see if you open the group.grp_office2 clicking on the info button from the developer-tools/state? Do you see brightness and color temperature when turning the lights on with the global toggle?

**Comment by xaviml** [comment]
Hi @corgan2222,

Could you resolve this issue? If no further comments about it, I will close it.

Thanks :)
