### ISSUE TITLE
Can't install from HACS

### ISSUE THREAD

**Issue by mr-blip** [xaviml/z2m_ikea_controller#7]
Hello,

I can't see the project in HACS (searching for z2m ikea).
Also can't add the custom repo manually (xaviml/z2m_ikea_controller).
I think is because it's looking for this URL:

https://api.github.com/repos/xaviml/z2m_ikea_controller/contents/custom_components

**Comment by xaviml** [comment]
Hi there,

Which version of HACS are you using? I am using the latest release of HACS (v0.20.7) and I see it in there. This is what I see: 
![here](https://user-images.githubusercontent.com/3974003/71979462-1458e800-321e-11ea-9e63-dedd27e3935f.png)

Furthermore, if you try to add it manually, HACS shows an error saying that the app is on the store, I see this:
![here](https://user-images.githubusercontent.com/3974003/71979579-58e48380-321e-11ea-9726-8fd88aaa40e9.png)

**Comment by mr-blip** [comment]
Found the problem. Installed HACS without AppDaemon support. 
Would be great if you add that info to the project's README. 

Thanks!
